services:
  server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 9090:9090
  envoy-proxy:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    ports:
      - 9901:9901
      - 8080:8080
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 3000:3000
    